name: Deploy to Azure Workflow

on:
 push:
    branches:
    - master
    paths:
      - MasterTemplate/*
env:
   AZURE_GROUP_NAME: Test-RG
jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - name: Git - Get Sources
      uses: actions/checkout@master

    - name: Azure - Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az group deployment create -n ghaction -g ${{ env.AZURE_GROUP_NAME }} --template-uri https://raw.githubusercontent.com/ghostme/AzureAssets/master/Networking/Deploymenturi.json
 
    
