name: Deploy to Azure Workflow

on:
 push:
    branches:
    - master
    paths:
      - MasterTemplate/*
env:
   SOURCE_FOLDER: /MasterTemplate/*
jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - name: Git - Get Sources
      uses: actions/checkout@master

    - name: Azure - Login
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
       az storage blob upload-batch -d github --account-name dccxxsihqdjssceg7a -s ${{ env.SOURCE_FOLDER }} --pattern "*.json" --destination-path MasterTemplate/
 
    
