name: Deploy to Azure Workflow

on:
 push:
    branches:
    - master
    path:
      - MasterTemplate/*

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    steps:
    - name: Git - Get Sources
      uses: actions/checkout@master

    - name: Azure - Login
      uses: Azure/github-actions/login@master
      env:
        AZURE_SUBSCRIPTION: Visual Studio Ultimate with MSDN
        AZURE_SERVICE_APP_ID: ${ { secrets.AZURE_SERVICE_APP_ID } }
        AZURE_SERVICE_PASSWORD: ${ { secrets.AZURE_SERVICE_PASSWORD } }
        AZURE_SERVICE_TENANT: ${ { secrets.AZURE_SERVICE_TENANT } }

    - name: Azure - Deploy ARM Template
      uses: Azure/github-actions/arm@master
      env:
        AZURE_RESOURCE_GROUP: github-actions
        AZURE_TEMPLATE_LOCATION: ./Networking/Deploymenturi.json
